
package soap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4.redhat-1
 * Thu Sep 21 20:00:51 CEST 2023
 * Generated source version: 3.1.4.redhat-1
 */

@XmlRootElement(name = "saluta", namespace = "http://soap/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "saluta", namespace = "http://soap/")

public class Saluta {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

